controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_posts:
    path: /post
    controller: App\Controller\PostController::index
    methods: [GET]
